name: doromochi
version: '0.1.0.0'
category: Desktop
author: aiya000
maintainer: aiya000
copyright: 2018 aiya000
license: MIT
homepage: https://github.com/aiya000/hs-doromochi
description: A supporter for your pomodoro technique with Tohoku Zunko
synopsis: A pomodoro technique app （・ω・）

dependencies:
  - base >=4.7 && <5
  - data-default
  - here
  - lens
  - rio
  - suspend
  - threepenny-gui
  - time
  - timers

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wno-name-shadowing
  - -Wno-orphans
  - -Wno-unused-do-bind
  - -Wredundant-constraints
  - -fprint-explicit-kinds
  - -fprint-potential-instances

default-extensions:
  - AutoDeriveTypeable
  - BangPatterns
  - BinaryLiterals
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DoAndIfThenElse
  - EmptyDataDecls
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - PartialTypeSignatures
  - PatternGuards
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeFamilies
  - TypeSynonymInstances
  - ViewPatterns

library:
  source-dirs: src

executables:
  doromochi:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies: doromochi

tests:
  doctest:
    main: DocTest.hs
    source-dirs:
      - test/doctest
      - src
    dependencies:
      - doctest
  tasty-test:
    main: Tasty.hs
    source-dirs:
      - test/tasty
      - src
    dependencies:
      - tasty
      - tasty-discover
